version: 2


build:
  os: "ubuntu-22.04"
  tools:
    python: 
          version: "3.8"


mkdocs:
  configuration: mkdocs.yml

python:
   version: "3.8"
   install:
   - requirements: requirements.txt
